/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import MyUtil.MyUtil;
import dao.CategoryDAO;
import dao.ProductDAO;
import dao.RoleDAO;
import java.awt.Font;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import model.Category;
import model.Product;
import model.Role;

/**
 *
 * @author LEGION 5 PRO
 */
public class ManageRole extends javax.swing.JFrame {

    /**
     * Creates new form ViewEditDeleteProduct
     */
    public ManageRole() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        
        btnLuu.setEnabled(false);
        btnXoa.setEnabled(false);
        
        jTable1.getTableHeader().setFont( new Font( "Arial" , Font.BOLD, 18 ));
        jTable1.setRowHeight(25);
        
//        jTable1.getColumn(0).setPreferredWidth(50);
//        jTable1.getColumn(1).setPreferredWidth(150);
//        jTable1.getColumn(2).setPreferredWidth(100);
//        jTable1.getColumn(3).setPreferredWidth(180);
        
        MyUtil.setJTableColumnsWidth(jTable1, 480, 10, 30, 30, 30);
        ImageIcon icon = new ImageIcon("src/images/full-page-background.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon sicon = new ImageIcon(imgScale);
        jLabel6.setIcon(sicon);
    }
    public void validateFiels(){
        String tenChucVu = txtTenChucVu.getText();
        String CongViec = txtCongViec.getText();
        String Luong =  txtLuong.getText();
        if(!tenChucVu.equals("")&&!CongViec.equals("")&&!Luong.equals("")){
            btnLuu.setEnabled(true);
        }
        else{
            btnLuu.setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbTenChucVu = new javax.swing.JLabel();
        lbLuong = new javax.swing.JLabel();
        lbCongViec = new javax.swing.JLabel();
        txtTenChucVu = new javax.swing.JTextField();
        txtCongViec = new javax.swing.JTextField();
        lbID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtLuong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view edit delete product.png"))); // NOI18N
        jLabel1.setText("Quản Lý Chức Vụ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 18, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 10, 42, 32));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 120, -1));

        lbTenChucVu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTenChucVu.setText("Tên Chức Vụ");
        getContentPane().add(lbTenChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 141, -1));

        lbLuong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbLuong.setText("Lương");
        getContentPane().add(lbLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, -1, -1));

        lbCongViec.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCongViec.setText("Mô Tả Công Việc");
        getContentPane().add(lbCongViec, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, -1, -1));

        txtTenChucVu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTenChucVu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenChucVuKeyReleased(evt);
            }
        });
        getContentPane().add(txtTenChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 363, -1));

        txtCongViec.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCongViec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCongViecKeyReleased(evt);
            }
        });
        getContentPane().add(txtCongViec, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 363, -1));

        lbID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbID.setText("00");
        getContentPane().add(lbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Chức Vụ", "Lương", "Mô Tả Công Việc"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 199, 630, 600));

        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 130, 30));

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, 90, 30));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, 110, 30));

        txtLuong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLuongKeyReleased(evt);
            }
        });
        getContentPane().add(txtLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 363, -1));

        jLabel6.setText("jLabel3");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -420, 1810, 1590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int id = Integer.parseInt(lbID.getText());
        JLabel label = new JLabel("Bạn Thực Sự Muốn Xóa Chức Vụ Này ?");
        label.setFont(new Font("Arial", Font.BOLD, 14));
        int a = JOptionPane.showConfirmDialog(null, label,"SELECT",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(a==0){
            int kq = RoleDAO.getInstance().delete(id);
            if(kq>0){
                JLabel label2 = new JLabel("Xóa Chức Vụ Thành Công!");
                label.setFont(new Font("Arial", Font.BOLD, 14));
                JOptionPane.showMessageDialog(null,label2,"MESSAGE",JOptionPane.WARNING_MESSAGE );
            }
            setVisible(false);
            new ManageRole().setVisible(true);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtTenChucVuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenChucVuKeyReleased
        validateFiels();
    }//GEN-LAST:event_txtTenChucVuKeyReleased

    private void txtCongViecKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCongViecKeyReleased
        validateFiels();
    }//GEN-LAST:event_txtCongViecKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        ArrayList<Role> list2 = RoleDAO.getInstance().selectAll();
        Iterator<Role> itr2 = list2.iterator();
        while(itr2.hasNext()){
            Role role = itr2.next();
            dtm.addRow(new Object[]{
                role.getId(),role.getTenChucVu(),role.getLuong(),role.getCongViec()
            });
        }
    }//GEN-LAST:event_formComponentShown

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        Role role = new Role();
        int id = Integer.parseInt(lbID.getText());
        role.setId(id);
        role.setTenChucVu(txtTenChucVu.getText());
        role.setLuong(txtLuong.getText());
        role.setCongViec(txtCongViec.getText());
        int kq = RoleDAO.getInstance().insert(role);
        setVisible(false);
        new ManageRole().setVisible(true);
        if(kq > 0){
            JLabel label = new JLabel("Đã Lưu Chức Vụ !");
                label.setFont(new Font("Arial", Font.BOLD, 14));
            JOptionPane.showMessageDialog(null,label,"MESSAGE",JOptionPane.WARNING_MESSAGE );
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String id = model.getValueAt(index, 0).toString();
        lbID.setText(id);
       txtTenChucVu.setText(model.getValueAt(index, 1).toString());
       txtLuong.setText(model.getValueAt(index, 2).toString());
       txtCongViec.setText(model.getValueAt(index, 3).toString());
        btnLuu.setEnabled(true);
        btnXoa.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        new ManageRole().setVisible(true);
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                // Câu lệnh mà bạn muốn thực hiện sau khoảng thời gian
                setVisible(false);
            }
        };

        Timer timer = new Timer();
        int delay = 30; // Khoảng thời gian (đơn vị: mili giây) trước khi thực hiện câu lệnh
        timer.schedule(task, delay);
    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtLuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLuongKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuongKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbCongViec;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbLuong;
    private javax.swing.JLabel lbTenChucVu;
    private javax.swing.JTextField txtCongViec;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtTenChucVu;
    // End of variables declaration//GEN-END:variables
}
