/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.CategoryDAO;
import dao.ProductDAO;
import dao.RoleDAO;
import dao.UserDAO;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Category;
import model.Product;
import model.Role;
import model.User;

/**
 *
 * @author LEGION 5 PRO
 */
public class Signup extends javax.swing.JFrame {
    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String soDienThoaiPattern = "^[0-9]*$";
    /**
     * Creates new form Signup
     */
    public Signup() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        btnLuu.setEnabled(false);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        ImageIcon icon = new ImageIcon("src/images/first_page_background.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon sicon = new ImageIcon(imgScale);
        jLabel3.setIcon(sicon);
    }
    public void clear(){
        txtTen.setText("");
        txtEmail.setText("");
        txtSoDienThoai.setText("");
        txtDiaChi.setText("");
        txtMatKhau.setText("");
        comboBoxCauHoi.setSelectedIndex(-1);
        txtCauTraLoi.setText("");
        btnLuu.setEnabled(false);
    }
    public void validateFields(){
        String ten = txtTen.getText();
        String email = txtEmail.getText();
        String soDienThoai = txtSoDienThoai.getText();
        String diaChi = txtDiaChi.getText();
        String matKhau = txtMatKhau.getText();
        String cauHoiBaoMat = (String) comboBoxCauHoi.getSelectedItem();
        String cauTraLoi = txtCauTraLoi.getText();
        if(!ten.equals("")&&email.matches(emailPattern)&&soDienThoai.matches(soDienThoaiPattern)
                &&!soDienThoai.equals("")
                &&!diaChi.equals("")
                &&!matKhau.equals("")
                &&!cauHoiBaoMat.equals("")
                &&!cauTraLoi.equals("")){
            btnLuu.setEnabled(true);
        }
        else{
            btnLuu.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbTen = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lbSoDienThoai = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        lbDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        lbCauHoiBaoMat = new javax.swing.JLabel();
        lbMatKhau = new javax.swing.JLabel();
        lbChucVu = new javax.swing.JLabel();
        comboBoxCauHoi = new javax.swing.JComboBox<>();
        txtMatKhau = new javax.swing.JPasswordField();
        btnLuu = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnQuenMatKhau = new javax.swing.JButton();
        btnDangNhap = new javax.swing.JButton();
        lbCauTraLoi = new javax.swing.JLabel();
        txtCauTraLoi = new javax.swing.JTextField();
        comboBoxChucVu = new javax.swing.JComboBox<>();
        lbLuong = new javax.swing.JLabel();
        lbChucVu2 = new javax.swing.JLabel();
        lbHTCongViec = new javax.swing.JLabel();
        lbHTLuong = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Đăng Ký");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, -1, -1));

        lbTen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTen.setText("Họ Và Tên");
        getContentPane().add(lbTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 100, -1));

        txtTen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });
        txtTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenKeyReleased(evt);
            }
        });
        getContentPane().add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 330, -1));

        lbEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbEmail.setText("Email");
        getContentPane().add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, -1, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 330, -1));

        lbSoDienThoai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbSoDienThoai.setText("Số Điện Thoại");
        getContentPane().add(lbSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, -1, -1));

        txtSoDienThoai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtSoDienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoDienThoaiKeyReleased(evt);
            }
        });
        getContentPane().add(txtSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 330, -1));

        lbDiaChi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbDiaChi.setText("Địa Chỉ");
        getContentPane().add(lbDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 64, -1));

        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });
        txtDiaChi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiaChiKeyReleased(evt);
            }
        });
        getContentPane().add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 480, 330, -1));

        lbCauHoiBaoMat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCauHoiBaoMat.setText("Câu Hỏi Bảo mật");
        getContentPane().add(lbCauHoiBaoMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 560, -1, -1));

        lbMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMatKhau.setText("Mật Khẩu");
        getContentPane().add(lbMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, -1, -1));

        lbChucVu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbChucVu.setText("Chức Vụ");
        getContentPane().add(lbChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 640, -1, -1));

        comboBoxCauHoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboBoxCauHoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Món ăn sáng yêu thích của bạn ?", "Màu sắc yêu thích của bạn  ?", "Cầu thủ yêu thích của bạn ?", "Bài hát yêu thích của bạn ?" }));
        comboBoxCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCauHoiActionPerformed(evt);
            }
        });
        comboBoxCauHoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                comboBoxCauHoiKeyReleased(evt);
            }
        });
        getContentPane().add(comboBoxCauHoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 560, 330, -1));

        txtMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtMatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMatKhauKeyReleased(evt);
            }
        });
        getContentPane().add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, 330, -1));

        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 780, -1, -1));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 780, 100, -1));

        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 780, 120, -1));

        btnQuenMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnQuenMatKhau.setText("Quên Mật Khẩu ?");
        btnQuenMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuenMatKhauActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 840, -1, -1));

        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 840, 130, -1));

        lbCauTraLoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCauTraLoi.setText("Câu Trả Lời");
        getContentPane().add(lbCauTraLoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 600, -1, -1));

        txtCauTraLoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCauTraLoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCauTraLoiKeyReleased(evt);
            }
        });
        getContentPane().add(txtCauTraLoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 600, 330, -1));

        comboBoxChucVu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboBoxChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxChucVuActionPerformed(evt);
            }
        });
        comboBoxChucVu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                comboBoxChucVuKeyReleased(evt);
            }
        });
        getContentPane().add(comboBoxChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 640, 330, -1));

        lbLuong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbLuong.setText("Lương");
        getContentPane().add(lbLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 690, -1, -1));

        lbChucVu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbChucVu2.setText("Mô Tả Công Việc");
        getContentPane().add(lbChucVu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 730, -1, -1));

        lbHTCongViec.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbHTCongViec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbHTCongViec, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 730, 330, 30));

        lbHTLuong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbHTLuong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbHTLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 690, 330, 30));

        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1760, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed

    private void comboBoxCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCauHoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCauHoiActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        User user = new User();
        Role choose = RoleDAO.getInstance().getRoleByName((String)comboBoxChucVu.getSelectedItem());
        System.out.println(choose.getId());
        user.setTen(txtTen.getText());
        user.setEmail(txtEmail.getText());
        user.setSoDienThoai(txtSoDienThoai.getText());
        user.setDiaChi(txtDiaChi.getText());
        user.setMatKhau(txtMatKhau.getText());
        user.setCauHoiBaoMat((String) comboBoxCauHoi.getSelectedItem());
        user.setCauTraLoi(txtCauTraLoi.getText());
        user.setTinhTrang("false");
        user.setMaCV(choose.getId());
        int kq = UserDAO.getInstance().insert(user);
        clear();
        if(kq>0){
            JLabel label = new JLabel("Bạn Đã Đăng Kí Thành Công!");
        label.setFont(new Font("Arial", Font.BOLD, 14));
            JOptionPane.showMessageDialog(null, label,"THÔNG BÁO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        new Login().setVisible(true);
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                // Câu lệnh mà bạn muốn thực hiện sau khoảng thời gian
                setVisible(false);
            }
        };

        Timer timer = new Timer();
        int delay = 30; // Khoảng thời gian (đơn vị: mili giây) trước khi thực hiện câu lệnh
        timer.schedule(task, delay);
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        JLabel label = new JLabel("Bạn Có Thực Sự Muốn Đóng Ứng Dụng Này?");
        label.setFont(new Font("Arial", Font.BOLD, 14));
        int a = JOptionPane.showConfirmDialog(null, label,"SELECT",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtTenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenKeyReleased
        validateFields();
    }//GEN-LAST:event_txtTenKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        validateFields();
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtSoDienThoaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoDienThoaiKeyReleased
        validateFields();
    }//GEN-LAST:event_txtSoDienThoaiKeyReleased

    private void txtDiaChiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaChiKeyReleased
        validateFields();
    }//GEN-LAST:event_txtDiaChiKeyReleased

    private void txtMatKhauKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKhauKeyReleased
        validateFields();
    }//GEN-LAST:event_txtMatKhauKeyReleased

    private void comboBoxCauHoiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboBoxCauHoiKeyReleased
        validateFields();
    }//GEN-LAST:event_comboBoxCauHoiKeyReleased

    private void btnQuenMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuenMatKhauActionPerformed
        new ForgotPassword().setVisible(true);
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                // Câu lệnh mà bạn muốn thực hiện sau khoảng thời gian
                setVisible(false);
            }
        };

        Timer timer = new Timer();
        int delay = 30; // Khoảng thời gian (đơn vị: mili giây) trước khi thực hiện câu lệnh
        timer.schedule(task, delay);
    }//GEN-LAST:event_btnQuenMatKhauActionPerformed

    private void txtCauTraLoiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCauTraLoiKeyReleased
        validateFields();
    }//GEN-LAST:event_txtCauTraLoiKeyReleased

    private void comboBoxChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxChucVuActionPerformed
        Role choose = RoleDAO.getInstance().getRoleByName((String)comboBoxChucVu.getSelectedItem());
        lbHTLuong.setText(choose.getLuong());
        lbHTCongViec.setText(choose.getCongViec());
    }//GEN-LAST:event_comboBoxChucVuActionPerformed

    private void comboBoxChucVuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboBoxChucVuKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxChucVuKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        ArrayList<Role> list = RoleDAO.getInstance().selectAll();
        Iterator<Role> itr = list.iterator();
        while(itr.hasNext()){
            Role role = itr.next();
            if(!role.getTenChucVu().equals("Chu So Huu")){
                comboBoxChucVu.addItem(role.getTenChucVu());
            }
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnQuenMatKhau;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> comboBoxCauHoi;
    private javax.swing.JComboBox<String> comboBoxChucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbCauHoiBaoMat;
    private javax.swing.JLabel lbCauTraLoi;
    private javax.swing.JLabel lbChucVu;
    private javax.swing.JLabel lbChucVu2;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbHTCongViec;
    private javax.swing.JLabel lbHTLuong;
    private javax.swing.JLabel lbLuong;
    private javax.swing.JLabel lbMatKhau;
    private javax.swing.JLabel lbSoDienThoai;
    private javax.swing.JLabel lbTen;
    private javax.swing.JTextField txtCauTraLoi;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
