/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import MyUtil.MyUtil;
import dao.CategoryDAO;
import dao.ProductDAO;
import java.awt.Font;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import model.Category;
import model.Product;

/**
 *
 * @author LEGION 5 PRO
 */
public class ViewEditDeleteProduct extends javax.swing.JFrame {

    /**
     * Creates new form ViewEditDeleteProduct
     */
    public ViewEditDeleteProduct() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        
        btnThayDoi.setEnabled(false);
        btnXoa.setEnabled(false);
        
        jTable1.getTableHeader().setFont( new Font( "Arial" , Font.BOLD, 18 ));
        jTable1.setRowHeight(25);
        
//        jTable1.getColumn(0).setPreferredWidth(50);
//        jTable1.getColumn(1).setPreferredWidth(150);
//        jTable1.getColumn(2).setPreferredWidth(100);
//        jTable1.getColumn(3).setPreferredWidth(180);
        
        MyUtil.setJTableColumnsWidth(jTable1, 480, 10, 30, 30, 30);
        ImageIcon icon = new ImageIcon("src/images/full-page-background.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon sicon = new ImageIcon(imgScale);
        jLabel6.setIcon(sicon);
    }
    public void validateFiels(){
        String tenSanPham = txtTenSanPham.getText();
        String giaThanh = txtGiaThanh.getText();
        String loaiHinh = (String) comboBoxLoaiHinh.getSelectedItem();
        if(!tenSanPham.equals("")&&!giaThanh.equals("")&&!loaiHinh.equals("")){
            btnThayDoi.setEnabled(true);
        }
        else{
            btnThayDoi.setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTenSanPham = new javax.swing.JTextField();
        txtGiaThanh = new javax.swing.JTextField();
        lbID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnThayDoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        comboBoxLoaiHinh = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view edit delete product.png"))); // NOI18N
        jLabel1.setText("Quản Lý Sản Phẩm");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 18, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 10, 42, 32));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Tên Sản Phẩm");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 141, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Loại Hình");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Giá Thành");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, -1, -1));

        txtTenSanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTenSanPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenSanPhamKeyReleased(evt);
            }
        });
        getContentPane().add(txtTenSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 363, -1));

        txtGiaThanh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtGiaThanh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiaThanhKeyReleased(evt);
            }
        });
        getContentPane().add(txtGiaThanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 363, -1));

        lbID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbID.setText("00");
        getContentPane().add(lbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên Sản Phẩm", "Loại Hình", "Giá Thành"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 199, 630, 600));

        btnThayDoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThayDoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnThayDoi.setText("Thay Đổi");
        btnThayDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThayDoiActionPerformed(evt);
            }
        });
        getContentPane().add(btnThayDoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 130, 30));

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, 90, 30));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, 110, 30));

        comboBoxLoaiHinh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboBoxLoaiHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxLoaiHinhActionPerformed(evt);
            }
        });
        comboBoxLoaiHinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                comboBoxLoaiHinhKeyReleased(evt);
            }
        });
        getContentPane().add(comboBoxLoaiHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 360, 30));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1710, 1090));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String id = lbID.getText();
        JLabel label = new JLabel("Bạn Thực Sự Muốn Xóa Món Này Khỏi Menu ?");
        label.setFont(new Font("Arial", Font.BOLD, 14));
        int a = JOptionPane.showConfirmDialog(null, label,"SELECT",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(a==0){
            int kq = ProductDAO.delete(id);
            if(kq>0){
                JLabel label2 = new JLabel("Xóa Món Thành Công!");
                label.setFont(new Font("Arial", Font.BOLD, 14));
                JOptionPane.showMessageDialog(null,label2,"MESSAGE",JOptionPane.WARNING_MESSAGE );
            }
            setVisible(false);
            new ViewEditDeleteProduct().setVisible(true);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtTenSanPhamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenSanPhamKeyReleased
        validateFiels();
    }//GEN-LAST:event_txtTenSanPhamKeyReleased

    private void comboBoxLoaiHinhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboBoxLoaiHinhKeyReleased
        validateFiels();
    }//GEN-LAST:event_comboBoxLoaiHinhKeyReleased

    private void txtGiaThanhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiaThanhKeyReleased
        validateFiels();
    }//GEN-LAST:event_txtGiaThanhKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        ArrayList<Category> list = CategoryDAO.getInstance().selectAll();
        Iterator<Category> itr = list.iterator();
        while(itr.hasNext()){
            Category category = itr.next();
            comboBoxLoaiHinh.addItem(category.getTenLoaiHinh());
        }
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        ArrayList<Product> list2  = ProductDAO.selectAll();
        Iterator<Product> itr2 = list2.iterator();
        while(itr2.hasNext()){
            Product product = itr2.next();
            dtm.addRow(new Object[]{
                product.getId(),product.getTenSanPham(),CategoryDAO.getInstance().selectByID(product.getLoaiHinh()).getTenLoaiHinh(),product.getGiaThanh()
            });
        }
    }//GEN-LAST:event_formComponentShown

    private void btnThayDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThayDoiActionPerformed
        Product product = new Product();
        int id = Integer.parseInt(lbID.getText());
        product.setId(id);
        product.setTenSanPham(txtTenSanPham.getText());
        product.setLoaiHinh(CategoryDAO.getInstance().getCategoryByName((String) comboBoxLoaiHinh.getSelectedItem()).getId());
        product.setGiaThanh(txtGiaThanh.getText());
        int kq = ProductDAO.update(product);
        setVisible(false);
        new ViewEditDeleteProduct().setVisible(true);
        if(kq > 0){
            JLabel label = new JLabel("Đã Thay Đổi Menu Thành Công!");
                label.setFont(new Font("Arial", Font.BOLD, 14));
            JOptionPane.showMessageDialog(null,label,"MESSAGE",JOptionPane.WARNING_MESSAGE );
        }
    }//GEN-LAST:event_btnThayDoiActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String id = model.getValueAt(index, 0).toString();
        lbID.setText(id);
        txtTenSanPham.setText(model.getValueAt(index, 1).toString());
        String loaiHinh = model.getValueAt(index, 2).toString();
        
        txtGiaThanh.setText(model.getValueAt(index, 3).toString());
        
        comboBoxLoaiHinh.removeAllItems();
        comboBoxLoaiHinh.addItem(loaiHinh);
         ArrayList<Category> list = CategoryDAO.getInstance().selectAll();
        Iterator<Category> itr = list.iterator();
        while(itr.hasNext()){
            Category category = itr.next();
            if(!category.getTenLoaiHinh().equals(loaiHinh)){
                comboBoxLoaiHinh.addItem(category.getTenLoaiHinh());
            }
        }
        btnThayDoi.setEnabled(true);
        btnXoa.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        new ViewEditDeleteProduct().setVisible(true);
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                // Câu lệnh mà bạn muốn thực hiện sau khoảng thời gian
                setVisible(false);
            }
        };

        Timer timer = new Timer();
        int delay = 30; // Khoảng thời gian (đơn vị: mili giây) trước khi thực hiện câu lệnh
        timer.schedule(task, delay);
    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboBoxLoaiHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxLoaiHinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxLoaiHinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEditDeleteProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnThayDoi;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> comboBoxLoaiHinh;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbID;
    private javax.swing.JTextField txtGiaThanh;
    private javax.swing.JTextField txtTenSanPham;
    // End of variables declaration//GEN-END:variables
}
